[package]
org = "healthcare"
name = "health.fhir.r4.international401.parameters"
version = "1.0.0"
distribution = "2201.8.1"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "Parameters", "r4", "health.fhir.r4.international401"]
template = true
